Implement Grip framework integration
Sija/raven.cr pull request #96
Opened 2024-12-01 06:18 UTC by Sija

This PR implements [Grip](https://github.com/grip-framework/grip) framework integration.
Resolves #88

/cc @grkek

2024-12-04 00:10 UTC, Sija commented
@grkek Could you please take a look and validate the implementation logic I've used?

2024-12-04 02:10 UTC, Sija commented on src/raven/integrations/grip/exception_handler.cr
> +      end
@grkek Ideally, I wouldn't need to duplicate this, although I couldn't find a cleaner way to associate the context with the matching route.

2024-12-04 02:10 UTC, Sija commented on src/raven/integrations/grip/exception_handler.cr
> +    #     router.insert(0, Raven::Grip::ExceptionHandler.new(self))
@grkek I assume that's the correct position to insert?

2025-01-05 05:04 UTC, grkek requested changes

2025-01-05 05:04 UTC, grkek commented on src/raven/integrations/grip/exception_handler.cr
> +      end
This looks just fine, this is what I do when I want to test the routes.

2025-01-05 05:04 UTC, grkek commented on src/raven/integrations/grip/exception_handler.cr
> +    #     router.insert(0, Raven::Grip::ExceptionHandler.new(self))
I would say `router.insert(1, Raven::Grip::ExceptionHandler.new(self))` is a lot better since you do not cut-off the original exception handler to handle all of the possible exceptions.

2025-01-05 05:16 UTC, Sija commented on src/raven/integrations/grip/exception_handler.cr
> +    #     router.insert(0, Raven::Grip::ExceptionHandler.new(self))
Original error handler is still being run, just further down the call chain.

2026-01-10 13:41 UTC, Sija commented
Not relevant anymore, closing.

2026-01-10 13:41 UTC, closed without merging